repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
      - id: ruff-check
        name: ruff-check
        entry: ruff check
        language: system
        types: [python]
        args: [--force-exclude, --fix, --exit-non-zero-on-fix]
        stages: [commit, push, manual]
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit, push, manual]