services:

  database:
    container_name: pyhnix-postgres
    image: postgres:16-alpine
    hostname: postgres
    restart: always
    volumes:
      - pyhnix-postgres:/var/lib/postgresql/data
    env_file: .env
  
  bot:
    container_name: pyhnix-bot
    image: pyhnix:v1
    restart: "no"
    volumes:
      - pyhnix-logs:/app/bot/.records
    env_file: .env
    profiles: [bot]

volumes:
  pyhnix-postgres:
    name: "pyhnix-database"

  pyhnix-logs:
