version: "3.8"
services:

  database:
    container_name: pyhnix-postgres
    image: postgres
    hostname: pyhnix-postgres
    restart: always
    volumes:
      - pyhnix-postgres:/var/lib/postgresql/data
    env_file: .env
  
  bot:
    container_name: pyhnix-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    profiles:
      - build
    volumes:
      - /.data/pyhnix/bot/records:/bot/.records
    env_file: .env

volumes:
  pyhnix-postgres:
    name: "pyhnix-database"
