version: "3.8"
services:

  database:
    container_name: pyhnix-postgres
    build:
      context: .
      dockerfile: Dockerfile.database
    hostname: pyhnix-postgres
    restart: always
    volumes:
      - pyhnix-postgres:/var/lib/postgresql/data
    env_file: .env
  
  bot:
    container_name: pyhnix-bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: "no"
    volumes:
      - pyhnix-logs:/app/bot/.records
    env_file: .env

volumes:
  pyhnix-postgres:
    name: "pyhnix-database"

  pyhnix-logs:
