[tool.black]
line-length = 80
target-version = ['py310']

[tool.isort]
line_length = 120
profile = "black"
skip_gitignore = true

[tool.pyright]
pythonVersion = "3.10"
useLibraryCodeForTypes = true
typeCheckingMode = "basic"
ignore = [
    'ext/embedbuilder.py'
]