
CREATE TABLE IF NOT EXISTS team (
    name VARCHAR(50) NOT NULL,
    guildid BIGINT NOT NULL,
    lead_roleid BIGINT,
    member_roleid BIGINT,
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    UNIQUE(name, guildid),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS team_member (
    teamid INTEGER NOT NULL REFERENCES team(id) ON DELETE CASCADE,
    userid BIGINT NOT NULL,

    PRIMARY KEY(teamid)
);