#!/bin/bash

# Ensure docker
# Build docker image for pyhnix with tag pyhnix
# Copy docker-compose file to /opt/pyhnix/docker-compose.yml
# Copy service file to /etc/systemd/system/pyhnix.service
# Reload systemctl deamon
# Enable pyhnix.service
# Stop pyhnix.service if running
# Start pyhnix.service

DIR="$( dirname "${BASH_SOURCE[0]}" )"

( 
cd $DIR/..
/usr/bin/docker build -t pyhnix:v1 .
sudo mkdir -p /opt/pyhnix
sudo cp docker-compose.yml /opt/pyhnix/docker-compose.yml
sudo cp .env /opt/pyhnix/.env
sudo cp pyhnix.service /etc/systemd/system/pyhnix.service
)

# TODO: Run the migrater

sudo systemctl daemon-reload
sudo systemctl enable pyhnix.service
sudo systemctl stop pyhnix.service
sudo systemctl start pyhnix.service
