#!/bin/bash

# Not so complex however it is best to use this.

sudo runuser -l pyhnix -c "cd /opt/pyhnix && git pull && /opt/pyhnix/venv/bin/activate && poetry install --no-root && python scripts/migrate.py"
