#!/bin/bash

# Git Pull
# Disable pyhnix.service
# Run docker compose file with the database and preform database migrations
# Copy service and compose file to desired locations
# Reload systemctl daemon
# Stop service if started
# Start service
